frr version 6.0.2
frr defaults traditional
hostname vpodrouter
log syslog informational
service integrated-vtysh-config
!
password {REPLACE_WITH_PASSWORD}
enable password {REPLACE_WITH_PASSWORD}
!
router bgp 65001
 bgp router-id 10.0.0.1
 neighbor 172.27.11.2 remote-as 65003
 neighbor 172.27.11.2 password {REPLACE_WITH_PASSWORD} 
 neighbor 172.27.11.3 remote-as 65003
 neighbor 172.27.11.3 password {REPLACE_WITH_PASSWORD}
 neighbor 172.27.12.2 remote-as 65003
 neighbor 172.27.12.2 password {REPLACE_WITH_PASSWORD}
 neighbor 172.27.12.3 remote-as 65003
 neighbor 172.27.12.3 password {REPLACE_WITH_PASSWORD}
 neighbor 10.0.131.3 remote-as 65010
 neighbor 10.0.131.3 password {REPLACE_WITH_PASSWORD}
 neighbor 10.0.231.3 remote-as 65020
 neighbor 10.0.231.3 password {REPLACE_WITH_PASSWORD} 
!
 address-family ipv4 unicast
  neighbor 172.27.11.2 default-originate
  neighbor 172.27.11.3 default-originate
  neighbor 172.27.12.2 default-originate
  neighbor 172.27.12.3 default-originate
  neighbor 10.0.131.3 default-originate
  neighbor 10.0.231.3 default-originate
  maximum-paths 4
 exit-address-family
!
router ospf
 redistribute connected
 redistribute static
 network 10.0.0.0/24 area 10
 default-information originate always metric 10
!
line vty
!
bfd
 peer 192.168.100.4 interface eth1
  receive-interval 1000
  transmit-interval 1000
  no shutdown
 !
 peer 192.168.100.3 interface eth1
  receive-interval 1000
  transmit-interval 1000
  no shutdown
 !
!
